# Generated by Django 3.0.3 on 2020-02-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_appliances', models.CharField(max_length=128)),
                ('kitchen_appliances', models.CharField(max_length=128)),
                ('entertainment', models.CharField(max_length=128)),
                ('computers', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=30)),
                ('warranty', models.IntegerField()),
                ('count', models.IntegerField()),
                ('brand_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itvdn_shop.Brand')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itvdn_shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('end_time', models.DateField(null=True)),
                ('start_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dishwasher',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itvdn_shop.Item')),
                ('energy_saving_class', models.CharField(default='A+', max_length=2)),
                ('power', models.IntegerField(default=0)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            bases=('itvdn_shop.item',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itvdn_shop.Item')),
                ('display', models.DecimalField(decimal_places=4, max_digits=5)),
                ('memory', models.IntegerField()),
                ('video_memory', models.IntegerField()),
                ('cpu', models.CharField(max_length=128)),
            ],
            bases=('itvdn_shop.item',),
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itvdn_shop.Item')),
                ('display', models.DecimalField(decimal_places=4, max_digits=5)),
                ('memory', models.IntegerField()),
                ('display_type', models.CharField(max_length=8)),
                ('smart_tv', models.BooleanField(verbose_name=False)),
            ],
            bases=('itvdn_shop.item',),
        ),
        migrations.CreateModel(
            name='VacuumCleaner',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itvdn_shop.Item')),
                ('noise_level', models.FloatField()),
                ('power', models.IntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('eco_engine', models.BooleanField(default=False)),
            ],
            bases=('itvdn_shop.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='promo',
            field=models.ManyToManyField(to='itvdn_shop.Promo'),
        ),
    ]
