# Generated by Django 3.0.3 on 2020-02-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itvdn_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='computers',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='household_appliances',
        ),
        migrations.RemoveField(
            model_name='category',
            name='kitchen_appliances',
        ),
    ]
