# Generated by Django 3.1.7 on 2021-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210329_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
